name: Deploy Python FastAPI to SmarterASP.NET (FTP)

on:
  push:
    branches: [ main ]
    # Optional: only run when Python API changes
    # paths:
    #   - 'python-api/**'
    #   - '.github/workflows/**'
  workflow_dispatch:

jobs:
  python_ftp_deploy:
    runs-on: ubuntu-latest

    env:
      # >>> SET THIS: path to your Python API folder ('.' if at repo root)
      PY_API_DIR: python-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: basic sanity check that your API has key files
      - name: Verify Python API folder
        run: |
          test -d "$PY_API_DIR" || (echo "Folder $PY_API_DIR not found" && exit 1)
          ls -la "$PY_API_DIR"

      # Deploy only the Python API folder to your site’s pyapi directory
      - name: Upload via FTP to SmarterASP.NET
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}          # e.g. ftp.site4now.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}  # e.g. /site/wwwroot/pyapi/
          local-dir: ${{ env.PY_API_DIR }}
          exclude: |
            **/.git*
            **/.github*
            **/__pycache__/
            **/venv/
            **/.venv/
            **/*.pyc
            **/*.pyo
            **/*.pyd
            **/.python-version
            **/.vscode/
            **/.DS_Store
            **/tests/**
            **/test/**
            **/docs/**
            **/node_modules/**
            **/dist/**
            **/build/**
